<?php /** @var \DNAFactory\FakeConfigurable\Block\Catalog\Product\Brother $block */
$brothers = $block->getBrothers();
?>

<?php if (!empty($brothers) || $block->includeCurrentProduct()):?>
<div id="fake-configurable" data-bind="scope: 'fakeConfigurable'">
    <!-- ko template: getTemplate() --><!-- /ko -->

    <div id="fake-configurable-items-wrapper" data-bind="css: { 'd-none': shouldShowBrothers }">
        <span class="label skeleton"></span>
        <div class="items-wrapper">
            <ul class="items d-flex">
                <?php foreach ($brothers as $brother):?>
                    <li class="item skeleton">
                    </li>
                <?php endforeach;?>

                <?php if ($block->includeCurrentProduct()):?>
                    <li class="item skeleton">
                    </li>
                <?php endif;?>
            </ul>
        </div>
    </div>

    <script type="text/x-magento-init">
       {
           "#fake-configurable": {
               "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
           }
       }
    </script>
</div>
<?php endif;?>
